## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('main-attribute-value', ['network', 'point-to-point'])
    obj.source = 'main-attribute-value.cc'

    obj = bld.create_ns3_program('initcwnd-wndscale-example', ['core','network', 'point-to-point', 'applications', 'internet', 'point-to-point-layout'])
    obj.source = 'initcwnd-wndscale-example.cc'
